# Generated by Django 5.0.1 on 2024-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_equipo_central_unidad_equipo_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
