# Generated by Django 5.0.1 on 2024-02-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_alter_equipo_name_alter_unidad_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trafo',
            fields=[
                ('equipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.equipo')),
                ('n_devanados', models.IntegerField(verbose_name='Número de Devanados')),
                ('kv_nominal_at', models.FloatField(verbose_name='KV Nominal AT')),
                ('kv_nominal_bt', models.FloatField(verbose_name='KV Nominal BT')),
                ('tension_kv', models.FloatField(verbose_name='Tensión KV')),
                ('elevacion_temperatura', models.FloatField(verbose_name='Elevación de Temperatura')),
            ],
            options={
                'verbose_name': 'Trafo',
                'verbose_name_plural': 'Trafos',
                'ordering': ['name'],
            },
            bases=('pruebas.equipo',),
        ),
    ]
