# Generated by Django 5.0.1 on 2024-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_trafo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='condicion_operacion',
            field=models.TextField(blank=True, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='indice_condicion',
            field=models.TextField(blank=True, verbose_name='Índice de Condición'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='problematica_operativa',
            field=models.TextField(blank=True, verbose_name='Problemática Operativa'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='razon_fuera_servicio',
            field=models.TextField(blank=True, verbose_name='Razón Fuera de Servicio'),
        ),
    ]
