# Generated by Django 5.0.1 on 2024-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_alter_equipo_condicion_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='unidades',
            field=models.ManyToManyField(blank=True, null=True, to='pruebas.unidad', verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='equipos',
            field=models.ManyToManyField(blank=True, null=True, to='pruebas.equipo', verbose_name='Equipos'),
        ),
    ]
