# Generated by Django 5.0.1 on 2024-02-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0007_remove_equipo_unidades_remove_unidad_equipos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('n_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie')),
                ('ano_puesta_servicio', models.IntegerField(verbose_name='Año de Puesta en Servicio')),
                ('condicion_operacion', models.TextField(blank=True, verbose_name='Condición de Operación')),
                ('razon_fuera_servicio', models.TextField(blank=True, verbose_name='Razón Fuera de Servicio')),
                ('problematica_operativa', models.TextField(blank=True, verbose_name='Problemática Operativa')),
                ('indice_condicion', models.TextField(blank=True, verbose_name='Índice de Condición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trafo',
            fields=[
                ('equipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.equipo')),
                ('n_devanados', models.IntegerField(verbose_name='Número de Devanados')),
                ('kv_nominal_at', models.FloatField(verbose_name='KV Nominal AT')),
                ('kv_nominal_bt', models.FloatField(verbose_name='KV Nominal BT')),
                ('tension_kv', models.FloatField(verbose_name='Tensión KV')),
                ('elevacion_temperatura', models.FloatField(verbose_name='Elevación de Temperatura')),
            ],
            options={
                'verbose_name': 'Trafo',
                'verbose_name_plural': 'Trafos',
                'ordering': ['name'],
            },
            bases=('pruebas.equipo',),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.central', verbose_name='Central')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnidadEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.equipo', verbose_name='Equipo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Unidad-Equipo',
                'verbose_name_plural': 'Unidades-Equipos',
                'ordering': ['unidad', 'equipo'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='unidades',
            field=models.ManyToManyField(through='pruebas.UnidadEquipo', to='pruebas.unidad', verbose_name='Unidades'),
        ),
    ]
