# Generated by Django 5.0.1 on 2024-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0009_remove_equipo_unidades_delete_unidadequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='unidades',
            field=models.ManyToManyField(to='pruebas.unidad', verbose_name='Unidades'),
        ),
    ]
