# Generated by Django 5.0.1 on 2024-02-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0011_impedancia_mva_tiposervicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='impedancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.impedancia', verbose_name='Impedancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafo',
            name='mva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.mva', verbose_name='MVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafo',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.tiposervicio', verbose_name='Tipo de Servicio'),
            preserve_default=False,
        ),
    ]
