# Generated by Django 5.0.1 on 2024-02-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0012_trafo_impedancia_trafo_mva_trafo_tipo_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='ElectricaTrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField(verbose_name='Fecha de Prueba')),
                ('procesado_por', models.CharField(max_length=255, unique=True, verbose_name='Procesado por')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.trafo', verbose_name='Trafo')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba', verbose_name='Prueba')),
            ],
            options={
                'verbose_name': 'Prueba Eléctrica de Trafos',
                'verbose_name_plural': 'Pruebas Eléctricas de Trafos',
                'ordering': ['fecha_prueba'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_1', models.FloatField(verbose_name='Zona 1')),
                ('zona_2', models.FloatField(verbose_name='Zona 2')),
                ('zona_3', models.FloatField(verbose_name='Zona 3')),
                ('zona_4', models.FloatField(verbose_name='Zona 4')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('electrica_trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.electricatrafo', verbose_name='Prueba Eléctrica de Trafos')),
            ],
            options={
                'verbose_name': 'Respuesta de Frecuencia',
                'verbose_name_plural': 'Respuestas de Frecuencia',
            },
        ),
    ]
