# Generated by Django 5.0.1 on 2024-02-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0015_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricaTrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField(verbose_name='Fecha de Prueba')),
                ('procesado_por', models.CharField(max_length=255, unique=True, verbose_name='Procesado por')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba', verbose_name='Prueba')),
            ],
            options={
                'verbose_name': 'Prueba Eléctrica de Trafos',
                'verbose_name_plural': 'Pruebas Eléctricas de Trafos',
                'ordering': ['fecha_prueba', 'prueba__matricula', 'prueba__trafo', 'prueba__trafo__unidades', 'prueba__trafo__unidades__central'],
            },
        ),
    ]
