# Generated by Django 5.0.1 on 2024-02-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0018_conexion_configuracion_enfriamiento_estatusrevision_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstatusRevision',
        ),
    ]
