# Generated by Django 5.0.1 on 2024-02-08 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0019_delete_estatusrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='configuracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.configuracion', verbose_name='Configuración'),
            preserve_default=False,
        ),
    ]
