# Generated by Django 5.0.1 on 2024-02-08 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0020_trafo_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='fase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.fase', verbose_name='Fase'),
            preserve_default=False,
        ),
    ]
