# Generated by Django 5.0.1 on 2024-02-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0021_trafo_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='conexion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.conexion', verbose_name='Conexión'),
            preserve_default=False,
        ),
    ]
