# Generated by Django 5.0.1 on 2024-02-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0022_trafo_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='enfriamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.enfriamiento', verbose_name='Enfriamiento'),
            preserve_default=False,
        ),
    ]
