# Generated by Django 5.0.1 on 2024-02-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0026_alter_trafo_estatus_revision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricatrafo',
            options={'ordering': ['fecha_prueba', 'prueba__matricula'], 'verbose_name': 'Prueba Eléctrica de Trafos', 'verbose_name_plural': 'Pruebas Eléctricas de Trafos'},
        ),
    ]
