# Generated by Django 5.0.1 on 2024-02-10 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0027_alter_electricatrafo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estatus de Prueba',
                'verbose_name_plural': 'Estatus de Pruebas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CromatografiaGases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.prueba', verbose_name='Prueba')),
                ('estatus_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.estatusprueba', verbose_name='Estatus de Prueba')),
            ],
            options={
                'verbose_name': 'Cromatografía de Gases',
                'verbose_name_plural': 'Cromatografías de Gases',
                'ordering': ['prueba__matricula'],
            },
        ),
        migrations.CreateModel(
            name='CromatografiaGasesRelacionO2N2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.FloatField(blank=True, null=True, verbose_name='Edad')),
                ('o2', models.FloatField(blank=True, null=True, verbose_name='O2')),
                ('n2', models.FloatField(blank=True, null=True, verbose_name='N2')),
                ('o2entren2', models.FloatField(blank=True, null=True, verbose_name='O2 entre N2')),
                ('h2', models.FloatField(blank=True, null=True, verbose_name='H2')),
                ('ch4', models.FloatField(blank=True, null=True, verbose_name='CH4')),
                ('co', models.FloatField(blank=True, null=True, verbose_name='CO')),
                ('c2h6', models.FloatField(blank=True, null=True, verbose_name='C2H6')),
                ('co2', models.FloatField(blank=True, null=True, verbose_name='CO2')),
                ('c2h4', models.FloatField(blank=True, null=True, verbose_name='C2H4')),
                ('c2h2', models.FloatField(blank=True, null=True, verbose_name='C2H2')),
                ('total_gc', models.FloatField(blank=True, null=True, verbose_name='Total GC')),
                ('p_incremento', models.FloatField(blank=True, null=True, verbose_name='% Incremento')),
                ('p_tgc_referencia', models.FloatField(blank=True, null=True, verbose_name='% TGC Referencia')),
                ('p_tgc_ultimo', models.FloatField(blank=True, null=True, verbose_name='% TGC Último')),
                ('diferencial', models.FloatField(blank=True, null=True, verbose_name='Diferencial')),
                ('absoluto', models.FloatField(blank=True, null=True, verbose_name='Absoluto')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('cromatografia_gases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.cromatografiagases', verbose_name='Cromatografía de Gases')),
            ],
            options={
                'verbose_name': 'Relación O2/N2',
                'verbose_name_plural': 'Relaciones O2/N2',
                'ordering': ['cromatografia_gases__prueba__matricula'],
            },
        ),
        migrations.CreateModel(
            name='Diferencial_O2N2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.FloatField(blank=True, null=True, verbose_name='H2')),
                ('ch4', models.FloatField(blank=True, null=True, verbose_name='CH4')),
                ('co', models.FloatField(blank=True, null=True, verbose_name='CO')),
                ('c2h6', models.FloatField(blank=True, null=True, verbose_name='C2H6')),
                ('co2', models.FloatField(blank=True, null=True, verbose_name='CO2')),
                ('c2h4', models.FloatField(blank=True, null=True, verbose_name='C2H4')),
                ('c2h2', models.FloatField(blank=True, null=True, verbose_name='C2H2')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('cromatografia_gases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.cromatografiagases', verbose_name='Cromatografía de Gases')),
            ],
            options={
                'verbose_name': 'Diferencial O2/N2',
                'verbose_name_plural': 'Diferenciales O2/N2',
                'ordering': ['cromatografia_gases__prueba__matricula'],
            },
        ),
        migrations.CreateModel(
            name='VelocidadEntrePruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_entre_pruebas', models.FloatField(blank=True, null=True, verbose_name='Meses entre Pruebas')),
                ('h2', models.FloatField(blank=True, null=True, verbose_name='H2')),
                ('ch4', models.FloatField(blank=True, null=True, verbose_name='CH4')),
                ('co', models.FloatField(blank=True, null=True, verbose_name='CO')),
                ('c2h6', models.FloatField(blank=True, null=True, verbose_name='C2H6')),
                ('co2', models.FloatField(blank=True, null=True, verbose_name='CO2')),
                ('c2h4', models.FloatField(blank=True, null=True, verbose_name='C2H4')),
                ('c2h2', models.FloatField(blank=True, null=True, verbose_name='C2H2')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('cromatografia_gases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.cromatografiagases', verbose_name='Cromatografía de Gases')),
            ],
            options={
                'verbose_name': 'Velocidad entre Pruebas',
                'verbose_name_plural': 'Velocidades entre Pruebas',
                'ordering': ['cromatografia_gases__prueba__matricula'],
            },
        ),
    ]
