# Generated by Django 5.0.1 on 2024-02-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0028_estatusprueba_cromatografiagases_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diferencial_O2N2',
            new_name='DiferencialO2N2',
        ),
    ]
