# Generated by Django 5.0.1 on 2024-02-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0029_rename_diferencial_o2n2_diferencialo2n2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Accesorio',
                'verbose_name_plural': 'Tipos de Accesorios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalado', models.BooleanField(default=False, verbose_name='Instalado')),
                ('en_servicio', models.BooleanField(default=False, verbose_name='En Servicio')),
                ('razon_fuera_servicio', models.TextField(blank=True, verbose_name='Razón Fuera de Servicio')),
                ('trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.trafo', verbose_name='Trafo')),
                ('tipo_accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.tipoaccesorio', verbose_name='Tipo de Accesorio')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
                'ordering': ['tipo_accesorio'],
            },
        ),
    ]
