# Generated by Django 5.0.1 on 2024-02-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0030_tipoaccesorio_accesorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafo',
            name='tension_kv',
        ),
    ]
