# Generated by Django 5.0.1 on 2024-02-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0031_remove_trafo_tension_kv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_1', models.FloatField(default=0, verbose_name='Tensión 1')),
                ('tension_2', models.FloatField(default=0, verbose_name='Tensión 2')),
                ('tension_3', models.FloatField(default=0, verbose_name='Tensión 3')),
            ],
            options={
                'verbose_name': 'Tensión',
                'verbose_name_plural': 'Tensiones',
            },
        ),
    ]
