# Generated by Django 5.0.1 on 2024-02-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0032_tension'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='tension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pruebas.tension', verbose_name='Tensión kV'),
            preserve_default=False,
        ),
    ]
