# Generated by Django 5.0.1 on 2024-02-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0033_trafo_tension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='trafo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='pruebas.trafo', verbose_name='Trafo'),
        ),
        migrations.CreateModel(
            name='RespuestaFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_1', models.FloatField(verbose_name='Zona 1')),
                ('zona_2', models.FloatField(verbose_name='Zona 2')),
                ('zona_3', models.FloatField(verbose_name='Zona 3')),
                ('zona_4', models.FloatField(verbose_name='Zona 4')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('electrica_trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.electricatrafo', verbose_name='Prueba Eléctrica de Trafos')),
            ],
            options={
                'verbose_name': 'Respuesta de Frecuencia',
                'verbose_name_plural': 'Respuestas de Frecuencia',
            },
        ),
    ]
