# Generated by Django 5.0.1 on 2024-02-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0035_resistenciaaislamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resistenciaaislamiento',
            name='respuesta_frecuencia',
        ),
    ]
