# Generated by Django 5.0.1 on 2024-02-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0036_remove_resistenciaaislamiento_respuesta_frecuencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResistenciaAislamiento',
        ),
    ]
