# Generated by Django 5.0.1 on 2024-02-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0037_delete_resistenciaaislamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistenciaAislamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_ch', models.FloatField(verbose_name='DEV CH')),
                ('dev_chl', models.FloatField(verbose_name='DEV CHL')),
                ('dev_cl', models.FloatField(verbose_name='DEV CL')),
                ('dev_cht', models.FloatField(verbose_name='DEV CHT')),
                ('dev_ct', models.FloatField(verbose_name='DEV CT')),
                ('electrica_trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.electricatrafo', verbose_name='Prueba Eléctrica de Trafos')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento',
                'verbose_name_plural': 'Resistencias de Aislamiento',
            },
        ),
    ]
