# Generated by Django 5.0.1 on 2024-02-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0038_resistenciaaislamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistenciaAislamiento10min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_prueba', models.FloatField(verbose_name='Temperatura de Prueba')),
                ('corriente_medida', models.FloatField(verbose_name='Corriente Medida')),
                ('perdida_aislamiento', models.FloatField(verbose_name='Pérdida de Aislamiento')),
                ('factor_k', models.FloatField(verbose_name='Factor K')),
                ('indice_polarizacion', models.FloatField(verbose_name='Índice de Polarización')),
                ('indice_absorcion', models.FloatField(verbose_name='Índice de Absorción')),
                ('resistencia_aislamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.resistenciaaislamiento', verbose_name='Resistencia de Aislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - 10 min',
                'verbose_name_plural': 'Resistencias de Aislamiento - 10 min',
            },
        ),
        migrations.CreateModel(
            name='ResistenciaAislamiento1min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_prueba', models.FloatField(verbose_name='Temperatura de Prueba')),
                ('corriente_medida', models.FloatField(verbose_name='Corriente Medida')),
                ('perdida_aislamiento', models.FloatField(verbose_name='Pérdida de Aislamiento')),
                ('factor_k', models.FloatField(verbose_name='Factor K')),
                ('indice_polarizacion', models.FloatField(verbose_name='Índice de Polarización')),
                ('indice_absorcion', models.FloatField(verbose_name='Índice de Absorción')),
                ('resistencia_aislamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.resistenciaaislamiento', verbose_name='Resistencia de Aislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - 1 min',
                'verbose_name_plural': 'Resistencias de Aislamiento - 1 min',
            },
        ),
        migrations.CreateModel(
            name='ResistenciaAislamiento30seg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_prueba', models.FloatField(verbose_name='Temperatura de Prueba')),
                ('corriente_medida', models.FloatField(verbose_name='Corriente Medida')),
                ('perdida_aislamiento', models.FloatField(verbose_name='Pérdida de Aislamiento')),
                ('factor_k', models.FloatField(verbose_name='Factor K')),
                ('indice_polarizacion', models.FloatField(verbose_name='Índice de Polarización')),
                ('indice_absorcion', models.FloatField(verbose_name='Índice de Absorción')),
                ('resistencia_aislamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.resistenciaaislamiento', verbose_name='Resistencia de Aislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - 30 seg',
                'verbose_name_plural': 'Resistencias de Aislamiento - 30 seg',
            },
        ),
    ]
