# Generated by Django 5.0.1 on 2024-02-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0039_resistenciaaislamiento10min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resistenciaaislamiento1min',
            name='resistencia_aislamiento',
        ),
        migrations.RemoveField(
            model_name='resistenciaaislamiento30seg',
            name='resistencia_aislamiento',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamiento10min',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamiento1min',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamiento30seg',
        ),
    ]
