# Generated by Django 5.0.1 on 2024-02-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0040_remove_resistenciaaislamiento1min_resistencia_aislamiento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResistenciaAislamiento',
        ),
    ]
