# Generated by Django 5.0.1 on 2024-02-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0042_resistenciaaislamiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResistenciaAislamiento',
        ),
    ]
