# Generated by Django 5.0.1 on 2024-02-16 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0044_respuestafrecuencia_diferencia_realizacion_prueba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistenciaAislamientoCH',
            fields=[
                ('resistenciaaislamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.resistenciaaislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - CH',
                'verbose_name_plural': 'Resistencias de Aislamiento - CH',
            },
            bases=('pruebas.resistenciaaislamiento',),
        ),
    ]
