# Generated by Django 5.0.1 on 2024-02-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0046_resistenciaaislamientochl_resistenciaaislamientocht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resistenciaaislamientocht',
            name='resistenciaaislamiento_ptr',
        ),
        migrations.RemoveField(
            model_name='resistenciaaislamientocl',
            name='resistenciaaislamiento_ptr',
        ),
        migrations.RemoveField(
            model_name='resistenciaaislamientoct',
            name='resistenciaaislamiento_ptr',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamientoCHL',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamientoCHT',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamientoCL',
        ),
        migrations.DeleteModel(
            name='ResistenciaAislamientoCT',
        ),
    ]
