# Generated by Django 5.0.1 on 2024-02-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0047_remove_resistenciaaislamientocht_resistenciaaislamiento_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistenciaAislamientoCHL',
            fields=[
                ('resistenciaaislamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.resistenciaaislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - CHL',
                'verbose_name_plural': 'Resistencias de Aislamiento - CHL',
            },
            bases=('pruebas.resistenciaaislamiento',),
        ),
        migrations.CreateModel(
            name='ResistenciaAislamientoCHT',
            fields=[
                ('resistenciaaislamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.resistenciaaislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - CHT',
                'verbose_name_plural': 'Resistencias de Aislamiento - CHT',
            },
            bases=('pruebas.resistenciaaislamiento',),
        ),
        migrations.CreateModel(
            name='ResistenciaAislamientoCL',
            fields=[
                ('resistenciaaislamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.resistenciaaislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - CL',
                'verbose_name_plural': 'Resistencias de Aislamiento - CL',
            },
            bases=('pruebas.resistenciaaislamiento',),
        ),
        migrations.CreateModel(
            name='ResistenciaAislamientoCT',
            fields=[
                ('resistenciaaislamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebas.resistenciaaislamiento')),
            ],
            options={
                'verbose_name': 'Resistencia de Aislamiento - CT',
                'verbose_name_plural': 'Resistencias de Aislamiento - CT',
            },
            bases=('pruebas.resistenciaaislamiento',),
        ),
    ]
