# Generated by Django 5.0.1 on 2024-02-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0049_datosfp_datosfpch_datosfpchl_datosfpcl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfpch',
            name='electrica_trafo',
        ),
        migrations.RemoveField(
            model_name='datosfpchl',
            name='electrica_trafo',
        ),
        migrations.RemoveField(
            model_name='datosfpcl',
            name='electrica_trafo',
        ),
        migrations.DeleteModel(
            name='DatosFP',
        ),
        migrations.DeleteModel(
            name='DatosFPCH',
        ),
        migrations.DeleteModel(
            name='DatosFPCHL',
        ),
        migrations.DeleteModel(
            name='DatosFPCL',
        ),
    ]
