# Generated by Django 5.0.1 on 2024-02-19 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0051_datosfp_datosfpch_datosfpchl_datosfpcl'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFPCHT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_referencia', models.FloatField(blank=True, null=True, verbose_name='FP Referencia')),
                ('corriente_ma', models.FloatField(blank=True, null=True, verbose_name='Corriente (mA)')),
                ('watts', models.FloatField(blank=True, null=True, verbose_name='Watts')),
                ('fp', models.FloatField(blank=True, null=True, verbose_name='FP')),
                ('p_fp_placa', models.FloatField(blank=True, null=True, verbose_name='% FP Placa')),
                ('velocidad_cambio_fp_placa', models.FloatField(blank=True, null=True, verbose_name='Velocidad de Cambio FP Placa')),
                ('aceleracion_fp_placa', models.FloatField(blank=True, null=True, verbose_name='Aceleración FP Placa')),
                ('electrica_trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.electricatrafo', verbose_name='Prueba Eléctrica de Trafos')),
                ('tension_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.datosfp', verbose_name='Tensión de Prueba')),
            ],
            options={
                'verbose_name': 'Datos Factor de Potencia - CHT',
                'verbose_name_plural': 'Datos Factores de Potencia - CHT',
            },
        ),
        migrations.CreateModel(
            name='DatosFPCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_referencia', models.FloatField(blank=True, null=True, verbose_name='FP Referencia')),
                ('corriente_ma', models.FloatField(blank=True, null=True, verbose_name='Corriente (mA)')),
                ('watts', models.FloatField(blank=True, null=True, verbose_name='Watts')),
                ('fp', models.FloatField(blank=True, null=True, verbose_name='FP')),
                ('p_fp_placa', models.FloatField(blank=True, null=True, verbose_name='% FP Placa')),
                ('velocidad_cambio_fp_placa', models.FloatField(blank=True, null=True, verbose_name='Velocidad de Cambio FP Placa')),
                ('aceleracion_fp_placa', models.FloatField(blank=True, null=True, verbose_name='Aceleración FP Placa')),
                ('electrica_trafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.electricatrafo', verbose_name='Prueba Eléctrica de Trafos')),
                ('tension_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.datosfp', verbose_name='Tensión de Prueba')),
            ],
            options={
                'verbose_name': 'Datos Factor de Potencia - CT',
                'verbose_name_plural': 'Datos Factores de Potencia - CT',
            },
        ),
    ]
